# Imports and Datasets


In [15]:
# Imports
import numpy as np
import pandas as pd
from time import time

# Scikit-learn stuff
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import QuantileTransformer
from sklearn.neural_network import MLPRegressor

In [16]:
# Get conductange range data from file set_sweep.csv
names = ["addr", "pw", "vwl", "vbsl", "preread", "postread"]
data = pd.read_csv("/content/set_sweep.csv", names=names)
data.head(20)

addr            pw  vwl  vbsl        preread       postread
0      0  2.000000e-08  0.5   0.5  151240.470700  115068.986900
1      2  2.000000e-08  0.5   1.0  123855.302200  124977.565700
2      4  2.000000e-08  0.5   1.5  127236.989700  106676.196700
3      6  2.000000e-08  0.5   2.0   93031.982770  133852.645200
4      8  2.000000e-08  0.5   2.5   75606.517090   57549.247700
5     10  2.000000e-08  0.5   3.0   97572.302250   92171.401490
6     12  2.000000e-08  0.6   0.5   46314.963040   50373.876070
7     14  2.000000e-08  0.6   1.0  100303.315400  149505.440600
8     16  2.000000e-08  0.6   1.5  212694.720700   75614.854910
9     18  2.000000e-08  0.6   2.0    5747.716015    5608.268993
10    20  2.000000e-08  0.6   2.5   99390.597620   68173.473680
11    22  2.000000e-08  0.6   3.0  115261.443600   41095.737690
12    24  2.000000e-08  0.7   0.5  138166.881800  131530.809600
13    26  2.000000e-08  0.7   1.0   84032.373080   68859.159200
14    28  2.000000e-08  0.7   1.5   77354.814580   35775.406770
15    30  2.000000e-08  0.7   2.0  156872.819900   48530.561620
16    32  2.000000e-08  0.7   2.5  125683.593900   55771.120680
17    34  2.000000e-08  0.7   3.0    5568.287628    5506.209298
18    36  2.000000e-08  0.8   0.5  102392.493600  150220.804000
19    38  2.000000e-08  0.8   1.0  132950.036700  154280.498200

# Data Preprocessing

Let us first convert resistance values (pre-read and post-read) to conductance values, and scale each column so that the maximum value is 1.

In [17]:
# Convert resistance to conductance
data['preread'] = 1 / data['preread']
data['postread'] = 1 / data['postread']

In [18]:
# Creating scaled versions of the columns which have very large or very small scales
data['scaled_pw'] = data['pw'] / np.max(data['pw'])
data['scaled_preread'] = data['preread'] / np.max(data['preread'])
data['scaled_postread'] = data['postread'] / np.max(data['postread'])

In [19]:
# Take a peek at the preprocessed data
data.head(20)

addr            pw  vwl  vbsl   preread  postread  scaled_pw  \
0      0  2.000000e-08  0.5   0.5  0.000007  0.000009       0.01   
1      2  2.000000e-08  0.5   1.0  0.000008  0.000008       0.01   
2      4  2.000000e-08  0.5   1.5  0.000008  0.000009       0.01   
3      6  2.000000e-08  0.5   2.0  0.000011  0.000007       0.01   
4      8  2.000000e-08  0.5   2.5  0.000013  0.000017       0.01   
5     10  2.000000e-08  0.5   3.0  0.000010  0.000011       0.01   
6     12  2.000000e-08  0.6   0.5  0.000022  0.000020       0.01   
7     14  2.000000e-08  0.6   1.0  0.000010  0.000007       0.01   
8     16  2.000000e-08  0.6   1.5  0.000005  0.000013       0.01   
9     18  2.000000e-08  0.6   2.0  0.000174  0.000178       0.01   
10    20  2.000000e-08  0.6   2.5  0.000010  0.000015       0.01   
11    22  2.000000e-08  0.6   3.0  0.000009  0.000024       0.01   
12    24  2.000000e-08  0.7   0.5  0.000007  0.000008       0.01   
13    26  2.000000e-08  0.7   1.0  0.000012  0.000015       0.01   
14    28  2.000000e-08  0.7   1.5  0.000013  0.000028       0.01   
15    30  2.000000e-08  0.7   2.0  0.000006  0.000021       0.01   
16    32  2.000000e-08  0.7   2.5  0.000008  0.000018       0.01   
17    34  2.000000e-08  0.7   3.0  0.000180  0.000182       0.01   
18    36  2.000000e-08  0.8   0.5  0.000010  0.000007       0.01   
19    38  2.000000e-08  0.8   1.0  0.000008  0.000006       0.01   

    scaled_preread  scaled_postread  
0         0.034318         0.044375  
1         0.041906         0.040857  
2         0.040792         0.047866  
3         0.055790         0.038148  
4         0.068648         0.088728  
5         0.053194         0.055399  
6         0.112064         0.101366  
7         0.051746         0.034154  
8         0.024402         0.067529  
9         0.903011         0.910478  
10        0.052221         0.074900  
11        0.045030         0.124251  
12        0.037565         0.038821  
13        0.061765         0.074154  
14        0.067097         0.142729  
15        0.033086         0.105216  
16        0.041296         0.091556  
17        0.932109         0.927354  
18        0.050690         0.033991  
19        0.039039         0.033097

### Train Test Split
Here, we make a 70%-30% split of the data into training and testing datasets

In [32]:
# Train-test 70%-30% split
x = data[["scaled_preread","scaled_pw","vwl","vbsl"]].to_numpy()
y = data["scaled_postread"].to_numpy()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

###Training/Testing Model

In [33]:
# Training the MLP regressor
print("Training MLPRegressor...")
tic = time()
est = make_pipeline(
    QuantileTransformer(),
    MLPRegressor(
        hidden_layer_sizes=(45, 23),
        learning_rate_init=0.03,
        early_stopping=True,
        random_state=0,
    ),
)
est.fit(X_train, y_train)
print(f"Done in {time() - tic:.3f}s")
print(f"Test R2 score: {est.score(X_test, y_test):.5f}")

Training MLPRegressor...
Done in 5.512s
Test R2 score: 0.96434


In [34]:
# Root Mean Squared Error (RMSE) on training dataset
predictions = est.predict(X_train)
mean_squared_error(y_train, predictions, squared=False)

0.060925081217161114

In [35]:
# Mean Squared Error (MSE) on training dataset
mean_squared_error(y_train, predictions, squared=True)

0.003711865521317678

In [36]:
# Root Mean Squared Error (RMSE) on testing dataset
predictions = est.predict(X_test)
mean_squared_error(y_test, predictions, squared=False)

0.06042596846965017

In [37]:
# Mean Squared Error (MSE) on testing dataset
mean_squared_error(y_test, predictions, squared=True)

0.0036512976654951563

### Testing on subset of testing data where there was a significant change in conductance (>= 50%)

In [43]:
# Filter the testing data to a subset
# Condition: |preread - postread| >= 50%
condition = (np.abs(X_test[:,0] - y_test) >= 0.5)
cond_X_test, cond_y_test = X_test[condition], y_test[condition]
cond_X_test, cond_y_test

(array([[0.05662796, 0.02      , 2.9       , 2.5       ],
        [0.05354097, 0.2       , 3.3       , 3.        ],
        [0.03979135, 0.5       , 1.8       , 2.        ],
        ...,
        [0.0785674 , 1.        , 2.2       , 2.5       ],
        [0.03845998, 0.02      , 2.9       , 2.        ],
        [0.05285441, 0.1       , 2.8       , 3.        ]]),
 array([0.89600339, 0.83129014, 0.78324301, ..., 0.79498139, 0.78026736,
        0.88830014]))

In [ ]:
# Root Mean Squared Error (RMSE) on training dataset
predictions = est.predict(X_train)
mean_squared_error(y_train, predictions, squared=False)

0.060925081217161114

In [ ]:
# Mean Squared Error (MSE) on training dataset
mean_squared_error(y_train, predictions, squared=True)

0.003711865521317678

In [ ]:
# Root Mean Squared Error (RMSE) on testing dataset
predictions = est.predict(X_test)
mean_squared_error(y_test, predictions, squared=False)

0.06042596846965017

In [ ]:
# Mean Squared Error (MSE) on testing dataset
mean_squared_error(y_test, predictions, squared=True)

0.0036512976654951563

### Testing on subset of testing data where there was a miniscule change in conductance (<= 5%)

In [45]:
# Filter the testing data to a subset
# NOTE: the first column of X_test is preread conductance
# Condition: |preread - postread| <= 5%
condition = (np.abs(X_test[:,0] - y_test) <= 0.05)
cond_X_test, cond_y_test = X_test[condition], y_test[condition]
cond_X_test, cond_y_test

(array([[0.8943141 , 0.1       , 2.8       , 0.5       ],
        [0.15029053, 0.2       , 0.5       , 3.        ],
        [0.83693339, 0.1       , 1.4       , 1.        ],
        ...,
        [0.12809017, 0.01      , 1.2       , 1.        ],
        [0.0483151 , 0.1       , 1.6       , 0.5       ],
        [0.07737659, 0.02      , 2.9       , 0.5       ]]),
 array([0.87902953, 0.10470574, 0.80512214, ..., 0.08642385, 0.06558585,
        0.06720146]))

In [ ]:
# Root Mean Squared Error (RMSE) on training dataset
predictions = est.predict(X_train)
mean_squared_error(y_train, predictions, squared=False)

0.060925081217161114

In [ ]:
# Mean Squared Error (MSE) on training dataset
mean_squared_error(y_train, predictions, squared=True)

0.003711865521317678

In [ ]:
# Root Mean Squared Error (RMSE) on testing dataset
predictions = est.predict(X_test)
mean_squared_error(y_test, predictions, squared=False)

0.06042596846965017

In [ ]:
# Mean Squared Error (MSE) on testing dataset
mean_squared_error(y_test, predictions, squared=True)

0.0036512976654951563